version: "3.1"
services:
  db:
    image: postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
